---
deployment:
  tasks:
    - export DEPLOYPATH=/home/hyrumtech/flores.planner1events.com/
    - /bin/cp -R control $DEPLOYPATH
    - /bin/cp -R funciones $DEPLOYPATH
    - /bin/cp -R upload $DEPLOYPATH
    - /bin/cp -R vistas $DEPLOYPATH
    - /bin/cp -R xcrud $DEPLOYPATH
    - /bin/cp -R index.php $DEPLOYPATH